/**
 * Calibrate every stage's boss to the difficulty standard: a reader answering at the stage's target
 * accuracy (see schedule.ts) should win about CALIBRATION.targetWin of the time. For each stage the
 * boss hp/dps multiplier is found by bisection over simulated matches and written to src/bossCalibration.ts.
 *
 * usage: npm run calibrate -w @catfight/engine [-- <sims per probe>]
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { bossScale, REF_PLAYER, simulateMatch, STAGE_COUNT, stageAi, targetAccuracy, uniformUpgrades, type SimPlayer } from '../src/index.js';

export const CALIBRATION = { targetWin: 0.7, minScale: 0.25, maxScale: 3, iterations: 8, backoff: 0.95 };
const SIMS = Number(process.argv[2] ?? 60);

/** what the reference player owns at stage n: only the two starter cats early on, upgrades roughly one level per 10 stages */
export function refPlayer(n: number, accuracyDelta = 0): SimPlayer {
  return {
    secPerQuestion: REF_PLAYER.secPerQuestion,
    accuracy: Math.max(0.05, Math.min(0.99, targetAccuracy(n) + accuracyDelta)),
    strategy: n < 20 ? ['tank', 'archer'] : undefined,
    upgrades: uniformUpgrades(Math.min(10, Math.round(n / 10))),
  };
}

function winRate(n: number, p: SimPlayer, sims = SIMS): number {
  let w = 0;
  for (let i = 0; i < sims; i++) if (simulateMatch(p, stageAi(n), i + 1).winner === 'left') w++;
  return w / sims;
}

const out: Record<number, number> = {};
const report: string[] = [];
for (let n = 1; n <= STAGE_COUNT; n++) {
  const p = refPlayer(n);
  let lo = CALIBRATION.minScale;
  let hi = CALIBRATION.maxScale;
  // win rate falls as the boss gets stronger: bisect for the strongest boss the reference player still beats targetWin of the time
  for (let i = 0; i < CALIBRATION.iterations; i++) {
    const mid = (lo + hi) / 2;
    bossScale[n] = mid;
    if (winRate(n, p) >= CALIBRATION.targetWin) lo = mid;
    else hi = mid;
  }
  // the win rate can fall off a cliff right past the boundary: step back until the target holds with some margin
  let scale = lo * CALIBRATION.backoff;
  for (let i = 0; i < 6; i++) {
    bossScale[n] = +scale.toFixed(3);
    if (winRate(n, p) >= CALIBRATION.targetWin - 0.05 || scale <= CALIBRATION.minScale) break;
    scale = Math.max(CALIBRATION.minScale, scale * CALIBRATION.backoff);
  }
  out[n] = bossScale[n];
  const w0 = winRate(n, p);
  const wLow = winRate(n, refPlayer(n, -0.1));
  const wHigh = winRate(n, refPlayer(n, 0.1));
  report.push(`stage ${String(n).padStart(3)} acc ${Math.round(targetAccuracy(n) * 100)}%  scale ${out[n].toFixed(3).padStart(5)}  win ${Math.round(w0 * 100)}%  (-10%: ${Math.round(wLow * 100)}%, +10%: ${Math.round(wHigh * 100)}%)`);
  console.log(report[report.length - 1]);
}

const file = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../src/bossCalibration.ts');
const body = Object.entries(out).map(([k, v]) => `  ${k}: ${v},`).join('\n');
writeFileSync(
  file,
  `// generated by \`npm run calibrate -w @catfight/engine\`; do not edit by hand.\n` +
    `// per-stage boss hp/dps multiplier so the reference player at the stage's target accuracy wins about ${CALIBRATION.targetWin * 100}% (${SIMS} sims per probe).\n` +
    `export const BOSS_CALIBRATION: Record<number, number> = {\n${body}\n};\n`,
);
console.log(`wrote ${file}`);
